# This workflow will install Python dependencies, run tests, lint, build a Docker image, and deploy to GCP Cloud Run
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  workflow_dispatch:
    inputs:
      user:
        type: string

permissions:
  contents: read
  id-token: write # This is required for requesting the JWT

env:
  JFROG_TOKEN: ${{ secrets.JFROG_TOKEN }}

jobs:
  build-and-deploy:

    runs-on: [self-hosted, aks]

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pydevd-pycharm==233.13135.95

    

    - name: Lint with flake8
      if: ${{!env.ACT}}
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run Python script
      run: |
        python hello2.py "${{ github.event.inputs.user }}"

